# -*- coding: utf-8 -*-
"""api_init.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lIWbIWkRaYzOQBn_Ir2TxwmaR_h7-zWl
"""

import subprocess
cmd = ["uvicorn", "api:app"]
subprocess.Popen(cmd, close_fds=True)